### ISSUE TITLE
Update main urls.py and browser_app's views.py

### ISSUE THREAD

**Issue by apartisan** [LucianU/bud#21]
Include browser_app/urls.py in the main urls.py

Home page returns an error, so add HomePageView in Views and link it to browser_app's urls.

**Comment by apartisan** [comment]
from django.urls import include, path
from . import views

app_name = 'browser_app'

urlpatterns = [
    path("", views.HomePage.as_view(), name='index'),
]

**Comment by apartisan** [comment]
views.py

from django.shortcuts import render
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'browser_app/index.html'

**Comment by LucianU** [comment]
Fixed in ea866b526937288585fbb62d9a93fd0b5661dbe8
